package com.drools.example.measurement;

import org.apache.log4j.Logger;
global Logger logger;

rule "FIRE TRUCK ARRIVED"
    when
        FireTruck()
        $fire: Fire()
    then
        logger.info("Fire truck arrived!");
        retract($fire);
end

rule "FIRE TRUCK LEAVING"
    when
        $truck: FireTruck()
        not Fire()
    then
        logger.info("Fire truck leaving!");
        retract($truck);
end
