package com.drools.example.measurement;

import org.apache.log4j.Logger;
global Logger logger;

rule "INIT"
    when
    then
        insert(new Measurement(true, 180));
        logger.info("Initial rule fired");
end

rule "ALARMING MEASUREMENT DETECTED"
    when
        exists Measurement(smoke || temperature > 150)
    then
        insert(new Fire());
end

rule "RETRACT UNUSED MEASUREMENT"
    when
        $measurement: Measurement()
    then
        retract($measurement);
end
