package com.drools.example.helloworld;

import org.apache.log4j.Logger;
global Logger logger;

rule "HELLO"
    when
        $helloWorld: HelloWorld(type == Type.HELLO)
    then
        logger.info("Hello, World!");
        $helloWorld.setType(HelloWorld.Type.GOODBYE);
        update($helloWorld);
end

rule "GOODBYE"
    when
        HelloWorld(type == Type.GOODBYE)
    then
        logger.info("Goodbye, World!");
end
